### ISSUE TITLE
How to Getting Started with perseus

### ISSUE THREAD

**Issue by izzuddinraffar** [Khan/perseus#106]
Hi,I'm new in react and nodejs,
Here, I want trying to setup perseus on my localhost,I'm using windows platform.
I'm trying to give command **npm install make server PORT=9000**, but having an error like below.
So, I don't know how to do in correct way, thanks.
<img src="http://simpana.cloudhub.my/img/temp/error.png"/>

**Comment by alopatin** [comment]
Hello!

Those are actually two separate commands. Try running `npm install` first, then `make server PORT=9000` afterwards.

**Comment by izzud1655** [comment]
Hi, @alopatin , I have done those commands, but command not working on make server PORT=9000
1- npm install
<img src="http://simpana.cloudhub.my/img/temp/error2.png"/>

2- make server PORT=9000 
<img src="http://simpana.cloudhub.my/img/temp/error3.png"/>

**Comment by andrewpatterson3001** [comment]
@izzud1655 Can you show the rest of the second image where you ran `make server PORT=9000`? I would like to help if I can.

**Comment by broerjuang** [comment]
I also have an issue when starting Perseus on my local computer. 

```shell
...
ERROR in ./math-input/src/components/iconography/jump-out-denominator.js
Module not found: Error: Cannot resolve module 'react' in /Users/Me/projects/oss/perseus/math-input/src/components/iconography
 @ ./math-input/src/components/iconography/jump-out-denominator.js 6:12-28

ERROR in ./math-input/src/components/iconography/arrow.js
Module not found: Error: Cannot resolve module 'react' in /Users/Me/projects/oss/perseus/math-input/src/components/iconography
 @ ./math-input/src/components/iconography/arrow.js 6:12-28

webpack: Failed to compile
```

**Comment by jeremywiebe** [comment]
Closing this inactive, stale issue.
