### ISSUE TITLE
Can't make server & build

### ISSUE THREAD

**Issue by sieuks** [Khan/perseus#110]
hi, I am newbie.
i'm try accesse 'perseus' but can't make server PORT=9000 and make build.
this is error:
"+ process_begin: CreateProcess(NULL, rm -rf node_modules/react-components, ...) failed.
 + make (e=2): The system cannot find the file specified."
plesea help me.
thanks

**Comment by ariabuckles** [comment]
Based on `CreateProcess`, I'm guessing you're on windows. KA doesn't officially support perseus development on windows, but you might be able to get the [linux subsystem on windows 10](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide) to work (though that might be what you were already trying), or using [VirtualBox](https://www.virtualbox.org/) and a [windows virtual machine image](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

**Comment by sieuks** [comment]
Hi. Thank you for help me.
i'm tried on 'ubuntu' system, but have error when i 'make build' & 'make server'
this is error:
+ make server: " /usr/bin/env: node: No such file or directory
                         make: *** [server-offline] Error 127"
+make build: "make: ka-lint: Command not found
                        make: *** [lint] Error 127"
can you fix this error. please 
thank you so much
