### ISSUE TITLE
How to use perseus using react 16.4.1 ? 

### ISSUE THREAD

**Issue by thisisrajkumar** [Khan/perseus#118]
we are using react boilerplate ( https://github.com/react-boilerplate/react-boilerplate). we are trying to implement perseus in our application. we are using react 16.4.1. It's possible to work with perseus with react 16 ?

**Comment by thisisrajkumar** [comment]
Thank you. We are successfully installed perseus-configured. How to show the editor?

**Comment by jeremywiebe** [comment]
Closing as the updated Perseus now uses react 16.14.
