### ISSUE TITLE
run tests on travis-ci

### ISSUE THREAD

**Issue by kevinb7** [Khan/perseus#29]
Even if the tests are already being run on Jenkins internally, using travis-ci helps when accepting pull requests from external contributors.

**Comment by ariabuckles** [comment]
The tests actually aren't running on jenkins internally; I just run them on the command line, and have a hook in the Makefile for them to run anytime someone attempts to update perseus on the website :).

Having them on travis sounds like a good idea; and done: https://travis-ci.org/Khan/perseus :)

**Comment by kevinb7** [comment]
Thanks.
