### ISSUE TITLE
[Question] Has anyone noticed any weirdness using the React DevTools extension

### ISSUE THREAD

**Issue by kevinb7** [Khan/perseus#31]
I wanted to use the React DevTools extension to get a better idea of the structure of the app, but the extension seems to be giving weird results, e.g. the <Renderer> for "example-graphie-widget 1" does not appear as a descendent of <ItemEditor>.  I was going to file a bug on facebook/react-devtools, but I want to check here first to make sure I wasn't misunderstanding the structure of the Perseus.

**Comment by ariabuckles** [comment]
I sometimes get weird results from the react devtools, although reloading sometimes seems to fix that. Going from "inspect element" to the react devtools is a bit hit or miss, but sometimes works.

Right now widgets are showing up for me as part of the Renderer top level tree (which I believe is the questionRenderer property mounted by the ItemRenderer):

![image](https://cloud.githubusercontent.com/assets/1487889/6332818/040e1476-bb4e-11e4-8090-46477c877bcb.png)

**Comment by kevinb7** [comment]
I'm seeing the same thing.  I had a look at ItemEditor's render method and sure enough it's creating some ```<div>```s with ids (workarea, hintsarea, etc.) that are being used by the ItemRenderer to attach various renderers to those elements.  I guess what I expected was that since those components are mounted on elements that are descendants of ```ItemEditor``` is that they would appear in the React inspector as descendants of the ```ItemEditor``` as well.  Now that I understand what's going on here a bit better I should be able to create a minimal reproducible example and file an issue with react-devtools.

As a I was investigating this I happened upon ```this.rendererMountNode``` in ```EditorPage```.  It never gets attached to the DOM which is kind of strange.  Then I looked at ```ItemRenderer``` which doesn't do much in its ```render``` method but does a whole bunch of stuff which looks like rendering in the its ```update``` method.  I was wondering what things were set up this way.

**Comment by ariabuckles** [comment]
`ItemRenderer` mounts stuff into specific nodes on the website for compatibility with khan-exercises. Because of this, EditorPage just mounts the actual `ItemEditor` to a not-shown div, and the real content gets mounted with IDs. This is pretty bad, but it's how it works right now, and backwards-compatibility means changing it isn't trivial (but it would be nice to do eventually).

You should stop by [Gitter](https://gitter.im/Khan/perseus) and we can chat there, which is probably nicer than github issues.

**Comment by kevinb7** [comment]
Will do.
