### ISSUE TITLE
Touchmove position is not correct if set the body zoom attribute big than 1.

### ISSUE THREAD

**Issue by devon** [Khan/perseus#32]
The default font and button size is too small in retina tablet. So, I set the body with `zoom:2`. The touch move position is not correct after modify the zoom attribute.

Is there any way to zoom the exercises without change the zoom attribute of body?

Thank you.

**Comment by kevinb7** [comment]
If you're looking to just increase the font size it's probably best to add ```body { font-size: 2.0em }``` or something like that.  If you want to make everything bigger than I'd suggest using a viewport meta tag.  For more info see: https://developer.mozilla.org/en/docs/Mozilla/Mobile/Viewport_meta_tag.

**Comment by devon** [comment]
Text zoom works for me. Thank you.
