### ISSUE TITLE
Dolar sign in question content

### ISSUE THREAD

**Issue by fpereira1** [Khan/perseus#34]
Hi - I am debugging an issue that I think it could be a bug. 

In the following example, we are using a table and $ signs in each row. The issue is that Perseus sees it as an inline math notation.

http://khan.github.io/perseus/#content=%7B%22question%22%3A%7B%22content%22%3A%22Here's%20a%20test%5Cn%5CnItem%20%7C%20Price%5Cn-%20%7C%20-%5CnItem%20%7C%20%241%5CnItem%20%7C%20%242%22%2C%22images%22%3A%7B%7D%2C%22widgets%22%3A%7B%7D%7D%2C%22answerArea%22%3A%7B%22type%22%3A%22multiple%22%2C%22options%22%3A%7B%22content%22%3A%22%22%2C%22images%22%3A%7B%7D%2C%22widgets%22%3A%7B%7D%7D%2C%22calculator%22%3Afalse%7D%2C%22itemDataVersion%22%3A%7B%22major%22%3A0%2C%22minor%22%3A1%7D%2C%22hints%22%3A%5B%5D%7D

I've tried the following setup in mathjax, but it didn't cause a change in how the question is rendered.

```js
MathJax.Hub.Config({
  tex2jax: {
    inlineMath: [['$','$'], ['\\(','\\)']],
    processEscapes: true
  }
});
```

I understand now that katex creates this notation.   There are a number of other libraries, mathjax, [khan/katex](https://github.com/khan/katex), [khan/simple-markdown](https://github.com/khan/simple-markdown)

Are you able to point in the right direction on what triggers this issue?

**Comment by xymostech** [comment]
The `tex2jax` plugin in MathJax only affects how math is rendered on the initial page load, and we disable that plugin in perseus anyways, so that configuration change to MathJax won't affect the rendering of math. (See [src/init.js](https://github.com/Khan/perseus/blob/master/src/init.js#L16)

@ariabuckles is going to actually solve your problem, just wanted to let you know why your solution doesn't work.

**Comment by ariabuckles** [comment]
Hi @fpereira1!

As you found, Perseus uses dollar signs to denote math. If you want to get literal dollar signs, there are two ways:

1. You can escape them with a `\`, as in: `The egg cost \$2.00`
2. You can put them in math (also escaped): `The egg cost $\$2.00$`

Note that option 1 doesn't work on khan.github.io right now, but it does work on master; I haven't updated the demo in a long time.

If you really want to disable inline math parsing in code (which I don't recommend), you could remove the `math` rule from [src/perseus-markdown.jsx](https://github.com/Khan/perseus/blob/master/src/perseus-markdown.jsx).

@xymostech has more info about the mathjax aspects of our math parsing

**Comment by fpereira1** [comment]
@xymostech @ariabuckles thank you for the details on this one, that definately answers my question.

**Comment by ariabuckles** [comment]
Great!
