### ISSUE TITLE
table warning in perseus demo

### ISSUE THREAD

**Issue by fpereira1** [Khan/perseus#39]
Hi,

I am trying the example on http://khan.github.io/perseus/ and when I add a table from the insert template dropdown I get a react error that pops up as a alert and the error in the console is:

> Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of Renderer. See http://fb.me/react-warning-keys for more information.warning @ react-with-addons.js:560

Here's an example [example](http://khan.github.io/perseus/#content=%7B%22question%22%3A%7B%22content%22%3A%22%5Cn%5Cnheader%201%20%7C%20header%202%20%7C%20header%203%5Cn-%20%7C%20-%20%7C%20-%5Cndata%201%20%7C%20data%202%20%7C%20data%203%5Cndata%204%20%7C%20data%205%20%7C%20data%206%5Cndata%207%20%7C%20data%208%20%7C%20data%209%22%2C%22images%22%3A%7B%7D%2C%22widgets%22%3A%7B%7D%7D%2C%22answerArea%22%3A%7B%22type%22%3A%22multiple%22%2C%22options%22%3A%7B%22content%22%3A%22%22%2C%22images%22%3A%7B%7D%2C%22widgets%22%3A%7B%7D%7D%2C%22calculator%22%3Afalse%7D%2C%22itemDataVersion%22%3A%7B%22major%22%3A0%2C%22minor%22%3A1%7D%2C%22hints%22%3A%5B%5D%7D)

is this a known issue or only affecting the editor on the public github?

Thanks!

**Comment by kevinb7** [comment]
While this warning only shows up in dev mode, eventually this warning will turn into an exception when we upgrade React so it should be fixed.  Thanks for providing a reproduction case.  This particular issue is pretty easy to fix.

**Comment by ariabuckles** [comment]
@fpereira1 thanks! this is a known issue; we'll do our best to fix it before it becomes an issue in react :).

@kevinb7 this should actually be fixed in the latest version of https://github.com/khan/simple-markdown, which hasn't been integrated into perseus yet ( https://app.asana.com/0/30796766242465/30959300813446 ).

**Comment by ariabuckles** [comment]
This should be fixed now! Thanks for reporting it!

**Comment by fpereira1** [comment]
Awesome thanks, I should investigate and send a PR next time
