### ISSUE TITLE
Widget translations

### ISSUE THREAD

**Issue by aeby** [Khan/perseus#40]
Is there some place to find the widget translation files (i.e to translate this https://github.com/Khan/perseus/blob/master/src/widgets/radio.jsx#L233)? I'm working on an offline exercise viewer and would like to provide localized widgets.

**Comment by ariabuckles** [comment]
I don't think those files are public (and they're in a specific format even if they were). we have a great team on crowdin to create those translations and some crazy infrastructure to parse the js code and sync them to/from crowdin.
