### ISSUE TITLE
how do I use perseus to render my own question?

### ISSUE THREAD

**Issue by gideondsouza** [Khan/perseus#44]
So from the project Readme and the live demo I don't see how to use the questions I create.

I see how I can see a JSON view of the question, but is there a way (or a place/end-point) I can "feed" this serialized JSON question so that I can render it for later?

Lets say I want to create a localized economics test site based on the KA content. I want to be able to run and host this locally on a private local network. (Of course I'll give attribution), especially since it's based on KA's economics content.

(as a dev I'm quite familiar with HTML. JS, some python, C#....)

**Comment by gideondsouza** [comment]
Anyone one this?

**Comment by ariabuckles** [comment]
Sorry, I don't think anyone really follows Perseus' issues/PRs anymore (I don't work at KA anymore, though I do lurk on a couple of the open source repos still).

The main endpoints you want to be looking into are Perseus.EditorPage for editing and Perseus.ItemRenderer for rendering a question (in src/editor-page.jsx and src/item-renderer.jsx). The former can give you json with .serialize(), and the latter takes that json as props. See `test.html` and `testrender.html` for example usage of both of these.

It would be nice to clean up *a lot* of things and make perseus into something that's really easy to use for other people with good documentation, but it's not quite there yet (and Khan Academy has to focus on actually providing a great education first and foremost!). It's relatively stable if you use the top-level endpoints (EditorPage/ItemEditor and ItemRenderer, or EditorPage/ArticleEditor and ArticleRenderer), but the documentation is not good. the `*.html` pages should show some usage though, and `src/article-editor.jsx` renders both the article editor and renderer (in `_renderPreviewMode`). To dig into the source code you'd probably want to have a basic understanding of React, but a deep understanding shouldn't be necessary just to use the outer endpoints.

**Comment by gideondsouza** [comment]
Brilliant! Thanks @ariabuckles :) This is what I was hoping to get.

**Comment by ariabuckles** [comment]
yw!
