### ISSUE TITLE
Cannot add widgets

### ISSUE THREAD

**Issue by mahfoudsam** [Khan/perseus#46]
Hi, 

After a "make server", I cannot add widgets, here is the errors I get on the console : 

- First time I try to add a widget : "ReferenceError: createFragment is not defined"

- When I try to add other widgets : "Error: Invariant Violation: findComponentRoot(..., .0.2.0.0.1.2.1:$radio 1/=10.0.1): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``."

Can someone help with that ? thank you :)

**Comment by ariabuckles** [comment]
92ed59b6cb1897d44a0c112aecd826b3eb6e2d1b might have addressed this, although there are some other places in the code using React.addons.createFragment that might need to be cleaned up as well.
