### ISSUE TITLE
Documentation + Release information: How to share problems with students

### ISSUE THREAD

**Issue by Domiii** [Khan/perseus#52]
Can Perseus currently be used to publish problem sets for students on the Khan website? Or is it still in active development? And if so, when will it be available?

**Comment by xymostech** [comment]
Perseus is used to publish problem sets for students on the KA website, but is currently only accessible by the content creators who work at KA itself, or are partners of KA. We don't currently support other people using KA to publish problems for their own students. We might have better support for this eventually, but we're not planning for it in the near future.
