### ISSUE TITLE
Create interactive doc

### ISSUE THREAD

**Issue by devjoe** [Khan/perseus#60]
This may not be an actual issue.
Is it possible to use Perseus to create [this kind](https://www.khanacademy.org/math/precalculus/precalc-matrices/intro-to-matrices/a/intro-to-matrices) of interactive documentations ?
If not, will Perseus (or other project) support it in the future ?

**Comment by jaredly** [comment]
Yup! That article is written using perseus. We call them "Particles" (PerseusArticles).
You can see an article "harness" [here](https://github.com/Khan/perseus/blob/c7276148f7cee40b5a00598379b1cf8df0041262/article.html), which doesn't actually appear to be working at the moment :D

**Comment by ariabuckles** [comment]
There's a good chance that harness doesn't get updated with changes to test.html appropriately--if it's not working, checking the git log of test.html can probably yield hints. That said, I'll go see if I can debug this.

**Comment by ariabuckles** [comment]
article.html seems to be working for me (just a very cursory test though). you need to run `git submodule update --init` and `make server` to set up the server from the repo, then http://localhost:9000/article.html should get you the editing playground for articles.

**Comment by devjoe** [comment]
WOW~ it works !!

Thank you @ariabuckles @jaredly ~

**Comment by ariabuckles** [comment]
you're welcome~!
