### ISSUE TITLE
Updating code for new ka-lint rules

### ISSUE THREAD

**Issue by JJC1138** [Khan/perseus#65]
https://github.com/Khan/perseus/commit/20b4fb8ae5e86605ff25893ddecec47a826becad added TODOs for updating the code for the new ka-lint ESLint rules.

I'm looking to start doing some work on KA's open source projects and I thought updating the code for the new standards might be a nice way for me to explore the code while doing something useful.

Would that be alright if I take that on? I asked @csilvers (who added the TODOs) and he mentioned that some projects have policies on lint-only changes so I'm asking here :)

Thanks very much

**Comment by xymostech** [comment]
Hello @JJC1138! Getting rid of some of the lint in our files would definitely be helpful!

I'm gonna close this issue, but feel free to comment here or make new issues if you hit problems. Thanks for wanting to contribute!

**Comment by JJC1138** [comment]
Will do. Thanks!

**Comment by xymostech** [comment]
Hey @JJC1138, just a heads up, I just pushed a bunch of changes to perseus. Sorry if that messes up your lint changes! If you'd like to send your lint fixes in smaller chunks that would also make it easier for us to review.

**Comment by JJC1138** [comment]
Oh thanks for letting me know @xymostech. I don't think that should be too hard for me to merge since hopefully the difficult bits of the lint changes (figuring out prop types and such) will mostly still apply.

Sorry it's taking me longer than expected. I am getting familiar with the codebase, though, so that's good! :)

I've been doing one commit per lint rule to hopefully make reviewing a little easier (some of the rules are just mechanical, others deserve a bit more attention). I could push what I've done so far after I've rebased onto the new master, but since there's some risk of breakage I'd like to do some thorough testing to make sure I haven't messed anything up, and I was planning to do that at the end before I push.

I expect there's only about one more day's work to finish, so I think I might as well just get it done and do one PR for the lot? (Hopefully I'll be done by Monday morning PT.)

**Comment by xymostech** [comment]
One commit per lint rule sounds really useful for reviewing! And no problem for taking your time, we're glad for your help!

**Comment by JJC1138** [comment]
Hi again. I haven't finished this today (merging took a tad longer than I was expecting 😅) but hopefully tomorrow! I just thought I'd let you know in case you were expecting it. Thanks!

**Comment by xymostech** [comment]
:) no problem, thanks for the update
