### ISSUE TITLE
Cannot add hint from test.html

### ISSUE THREAD

**Issue by vhoangvu** [Khan/perseus#67]
I cannot add hint from test.html. The error is:
hint-renderer.jsx:36 Uncaught TypeError: Cannot read property 'newHintStyles' of undefined

I guess the related commit is [https://github.com/Khan/perseus/commit/76676428759dc7109f39e5a52eaccec81e8a8a30]

But don't know how to fix.

**Comment by jeremywiebe** [comment]
Closing this inactive, stale issue.
