### ISSUE TITLE
Pull request Travis builds fail because of attempt to decrypt demo deployment key

### ISSUE THREAD

**Issue by JJC1138** [Khan/perseus#76]
The [Travis build for my PR is failing](https://travis-ci.org/Khan/perseus/builds/131212389#L440) because the command to decrypt the deployment key fails. According to the [Travis docs](https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables) "Encrypted variables are not added to untrusted builds such as pull requests coming from another repository." which is reasonable enough.

I'd guess the fix for this is to move the decryption from the `before_script` Travis phase into the `after_success` phase after the check that the build isn't a pull request build?

**Comment by jeremywiebe** [comment]
Close outdated issue (we don't use Travis any longer). Please re-open if it continues to be an issue.
