### ISSUE TITLE
Help: Rendering the datastore. 

### ISSUE THREAD

**Issue by jamesBaker361** [Khan/perseus#81]
What function/component actually passes the datastore to the Widget Editor? Where is it in the project?

**Comment by kevinbarabash** [comment]
@jamesBaker361 have a look at https://github.com/Khan/perseus/blob/master/src/renderer-demo.jsx#L89-L95.  It shows how to use renderer to render a perseus exercise.  Not sure what `datastore` you're using.

**Comment by jamesBaker361** [comment]
@kevinbarabash  Oh thanks!

**Comment by kevinbarabash** [comment]
@jamesBaker361 sounds like you found that snippet helpful so I'm going to close this.
