### ISSUE TITLE
defaultQuestion not working

### ISSUE THREAD

**Issue by jamesBaker361** [Khan/perseus#83]
I tried putting a widget into defaultQuestion["widgets"] in demo-perseus.js in the hope the page would load with a specific widget pre-rendered. Instead, it was just blank. I tried changing 
const question = defaultQuestion, and it still yields nothing. What's going on?

**Comment by xymostech** [comment]
Hello @jamesBaker361. It sounds like you are trying to add widgets by manually adding them in the JSON. I'm not exactly sure what is going wrong, but have you tried adding the widgets using the demo editor, and then copying the output JSON (which you can see by checking the "Developer JSON Mode" check box)?

**Comment by jamesBaker361** [comment]
I've tried that, and it does work, but i need to be able to load the page, and already have the questions be rendered, without having the user input their own JSON.

**Comment by xymostech** [comment]
Did you try copying the output JSON from the editor page into the `defaultQuestion`?

**Comment by jamesBaker361** [comment]
@xymostech yeah i retried it, and turns out my problem was just a small, but impactful, syntax error. Whoops. Thanks anyway though!

**Comment by xymostech** [comment]
Great! Glad to hear it's working :)
