### ISSUE TITLE
expression widget unit test hangs

### ISSUE THREAD

**Issue by benkomalo** [Khan/perseus#90]
`node node_modules/mocha/bin/_mocha --reporter dot -r node/environment.js src/widgets/__tests__/expression-test.jsx` seems to hang

@crm416 @kevinbarabash - anything obvious that might be happening to you gents?

**Comment by benkomalo** [comment]
Hrm. It appears this was specific to node versions?
Downgrading to `v5.12.0` fixes things for me (was on `v6.5.0` when I filed this)

**Comment by kevinbarabash** [comment]
@benkomalo was there any console output when it hung?
