### ISSUE TITLE
Issues while live preview of exercise content on the perseus editor

### ISSUE THREAD

**Issue by bnk1990** [Khan/perseus#92]
I would like to see live preview of content  in the right side while I am creating in perseus editor.  However the box is showing empty. Please refer the image : http://imgur.com/a/cW2Tq

However, it used to work in older version (http://imgur.com/a/8lOAJ)

Appreciate your help.

**Comment by ariabuckles** [comment]
This looks like it's just an issue with the https://khan.github.io/perseus not including underscore correctly; the master branch's local server seems to work.

Someone might just need to update the github.io preview; in the mean time, you should be able to run your own copy locally using the instructions in the readme.

**Comment by bnk1990** [comment]
Thanks Aria. After including underscore and couple other frame-perseus.js dependencies, preview is working fine.

**Comment by ariabuckles** [comment]
Great! Sorry it's got weird dependency-stuff; never got around to fixing that.
